"""Self-check for world generation. Run: python test_worldgen.py

Everything here fails as *looks wrong* rather than as an exception, which is why
it is written down:

- The same seed has to build the same world. Chunks are generated by four
  worker threads, cached, dropped and regenerated; a column that comes back
  different is a seam you can walk into.
- A feature that straddles a chunk boundary is written twice, once by each
  chunk, from the same hash. If the two halves disagree you get a floating
  canopy or half a house. This is what the old generator got wrong by skipping
  edge trees outright, leaving a bare strip down every seam.
- Caves have to stay `SEAL_COVER` blocks under the surface. The far LOD fills in
  any air with less cover than that (fast_builder.seal_buried_air), so a cave
  that reaches closer to daylight would visibly close up as you walk away.
- Water only below sea level, and no air pocket underneath it.

Then it prints the biome mix and the per-chunk cost the tuning was done against.
"""
import collections
import math
import time

import numpy as np

from world.blocks import BLOCK_DTYPE, FACE_LAYER, OPAQUE
from world.fast_builder import AIR, SEAL_COVER, build_chunk_mesh_fast, make_mesh_buffers
from world.terrain_generator import (BIOME_NAMES, B_TREES, CAVE_ROOF,
                                     CHUNK_HEIGHT, CHUNK_SIZE, MIN_TERRAIN,
                                     PAD, SEA_LEVEL, WATER, V_WALL,
                                     column_biome, find_spawn, place_tree,
                                     surface_height, terrain_generator,
                                     village_check, village_site)

# Every leaf block in the table — the seam check counts these, and a canopy it
# does not know about is a canopy it cannot see get clipped.
LEAVES = (6, 54, 55, 56, 57, 58, 147, 148, 149, 150, 359)

# Natural ground: the top of a column that is neither vegetation nor built.
GROUND = (1, 2, 3, 4, 5, 12, 16, 20, 21, 22, 23, 24, 26, 27, 91, 125, 128,
          215, 219, 220, 221, 222)


def gen(chunk_x, chunk_z):
    blocks = np.zeros((CHUNK_SIZE, CHUNK_HEIGHT, CHUNK_SIZE), dtype=BLOCK_DTYPE)
    terrain_generator.generate_chunk_terrain(chunk_x, chunk_z, blocks)
    return blocks


def patch(x0, z0, n):
    return {(x, z): gen(x, z) for x in range(x0, x0 + n) for z in range(z0, z0 + n)}


def column_top(blocks, x, z):
    for y in range(CHUNK_HEIGHT - 1, -1, -1):
        if blocks[x, y, z] != AIR and blocks[x, y, z] != WATER:
            return y
    return -1


def check_deterministic():
    """A chunk generated twice, and generated again after its neighbours, is the
    same chunk. Nothing in the kernel may depend on what ran before it."""
    for chunk_x, chunk_z in ((0, 0), (37, -12), (-104, 61)):
        first = gen(chunk_x, chunk_z)
        assert np.array_equal(first, gen(chunk_x, chunk_z)), \
            f"chunk ({chunk_x}, {chunk_z}) generated differently the second time"
        gen(chunk_x + 1, chunk_z)
        assert np.array_equal(first, gen(chunk_x, chunk_z)), \
            "generating a neighbour changed the chunk"


def wooded_patch(n):
    """A patch where *every* chunk is dense forest.

    The seam profile below is a ratio between two column groups, so it needs a
    patch whose tree density does not vary across it — measured over a patch
    that happened to be half empty it swings between 0.5 and 1.8 on noise alone
    and says nothing about seams.
    """
    for chunk_x in range(0, 160, 6):
        for chunk_z in range(0, 160, 6):
            if all(B_TREES[column_biome(x * CHUNK_SIZE + 8, z * CHUNK_SIZE + 8)] > 280
                   for x in range(chunk_x, chunk_x + n)
                   for z in range(chunk_z, chunk_z + n)):
                return patch(chunk_x, chunk_z, n)
    raise AssertionError("found no solid forest to check chunk seams against")


def check_seams(chunks):
    """Trees are placed from a padded heightmap, so a canopy rooted next door is
    written by both chunks. The bug this catches is the visible bare strip the
    old generator left by refusing to place a tree whose canopy left the chunk.

    Measured as a profile across the chunk rather than edge-vs-middle: leaf
    density is binned by *offset within the chunk*, summed over every chunk in
    the patch and over both axes. Clipping shows up as a trough at offsets 0 and
    15, and binning this way averages the forest's own patchiness out instead of
    letting it swamp the signal.
    """
    profile = np.zeros(CHUNK_SIZE)
    for blocks in chunks.values():
        leaves = np.isin(blocks, LEAVES)
        profile += leaves.sum(axis=(1, 2))          # by x offset
        profile += leaves.sum(axis=(0, 1))          # by z offset
    assert profile.sum() > 4000, "not enough leaves in the patch to say anything"
    edge = (profile[0] + profile[CHUNK_SIZE - 1]) / 2
    middle = profile[6:10].mean()
    ratio = edge / max(1.0, middle)
    assert ratio > 0.6, (
        f"leaf density at the chunk edge is {ratio:.0%} of the middle — canopies "
        f"are being clipped at the seam. Profile: {profile.astype(int)}")
    return ratio


def check_caves(chunks):
    """No cave may come within SEAL_COVER blocks of the surface.

    Air directly under the top of a natural column can only be a cave — this
    generator has no overhangs, and vegetation and buildings are excluded by
    looking at what the top block is. The far LOD fills in anything shallower
    than this, so a breach here is a cave mouth that closes as you walk away.
    """
    assert CAVE_ROOF > SEAL_COVER, \
        "caves must be roofed by more than the far LOD is willing to fill in"
    checked = 0
    for blocks in chunks.values():
        for x in range(CHUNK_SIZE):
            for z in range(CHUNK_SIZE):
                top = column_top(blocks, x, z)
                if top < MIN_TERRAIN + CAVE_ROOF or blocks[x, top, z] not in GROUND:
                    continue
                checked += 1
                gap = blocks[x, top - SEAL_COVER:top, z]
                assert not np.any(gap == AIR), \
                    f"cave air {top} blocks up, within {SEAL_COVER} of the surface"
    assert checked > 500, "not enough natural columns to say anything"


def check_water(chunks):
    for blocks in chunks.values():
        water = np.argwhere(blocks == WATER)
        if len(water) == 0:
            continue
        assert water[:, 1].max() < SEA_LEVEL, "water above sea level"
        # Water rests on the sea bed, never over a hole. Caves *below* the bed
        # are fine and stay dry — we have no aquifers, so a cave that opened
        # into the sea would be a dry room with an ocean for a ceiling.
        for x, y, z in water:
            below = blocks[x, y - 1, z]
            assert below != AIR, f"water floating over air at ({x}, {y}, {z})"


def check_bounds(chunks):
    for blocks in chunks.values():
        for x in range(0, CHUNK_SIZE, 4):
            for z in range(0, CHUNK_SIZE, 4):
                top = column_top(blocks, x, z)
                assert MIN_TERRAIN <= top < CHUNK_HEIGHT - 8, f"column top at {top}"
                assert blocks[x, 0, z] == 31, "no bedrock floor"


# One block that only appears in one kind of building. A village that scores
# fewer than three of these is eight copies of the same box, which is what the
# single-template version was.
KIND_MARKERS = {'window': 256, 'library': 95, 'lamp': 102, 'farm': 20,
                'pen/roof': 101}


def check_village():
    """The nearest village is walled, varied, standing on the ground, and
    walkable from its own plaza."""
    for radius in range(1, 14):
        for region_x in range(-radius, radius + 1):
            for region_z in range(-radius, radius + 1):
                village_x, village_z = village_site(region_x, region_z)
                ok, floor_y, style = village_check(village_x, village_z)
                if not ok:
                    continue

                chunk_x, chunk_z = village_x // CHUNK_SIZE, village_z // CHUNK_SIZE
                around = patch(chunk_x - 2, chunk_z - 2, 5)
                walls = sum(int((b == V_WALL[style]).sum()) for b in around.values())
                assert walls > 40, f"village at {village_x},{village_z} has {walls} wall blocks"

                kinds = [name for name, block in KIND_MARKERS.items()
                         if any((b == block).any() for b in around.values())]
                assert len(kinds) >= 3, \
                    f"village is built from too few kinds of building: {kinds}"

                # Nothing floats. Buildings stand at their own plot's height now
                # rather than all at the village's, so the failure this guards
                # against is a house left hanging where the ground dropped away.
                for (cx, cz), b in around.items():
                    for x in range(CHUNK_SIZE):
                        for z in range(CHUNK_SIZE):
                            column = np.flatnonzero(b[x, :, z] == V_WALL[style])
                            if len(column) and column[0] > 1:
                                assert b[x, column[0] - 1, z] != AIR, \
                                    f"a wall floats over air at chunk {cx},{cz} {x},{z}"

                # You can walk off the plaza. The streets follow the terrain, so
                # this is no longer "the plaza is flat" but "the plaza has no
                # hole in it and does not step more than a block".
                middle = around[(chunk_x, chunk_z)]
                x, z = village_x % CHUNK_SIZE, village_z % CHUNK_SIZE
                for dx, dz in ((3, 0), (-3, 0), (0, 3), (0, -3)):
                    if not (0 <= x + dx < CHUNK_SIZE and 0 <= z + dz < CHUNK_SIZE):
                        continue
                    top = column_top(middle, x + dx, z + dz)
                    assert abs(top - floor_y) <= 3, \
                        f"the plaza steps {top - floor_y} blocks at ({dx}, {dz})"
                return village_x, village_z, style, walls, kinds
    raise AssertionError("no village anywhere in 27x27 regions")


def check_spawn():
    """Spawn is dry, and the height it was picked from is the height the chunk
    actually built.

    Those are the same assertion. `surface_height` reads the climate lattice
    that the chunk kernel samples rather than the noise underneath it; reading
    the noise directly gave a different world and dropped the player several
    blocks inside a hill.
    """
    x, y, z = find_spawn()
    assert y > SEA_LEVEL, f"spawn at y={y} is under the sea"

    # floor, not int: find_spawn returns the block centre, so a spawn west or
    # north of the origin comes back as -86.5 and int() truncates that to the
    # column next door. The world only had to grow an ocean around the origin
    # for this to start firing.
    x, z = math.floor(x), math.floor(z)
    blocks = gen(x // CHUNK_SIZE, z // CHUNK_SIZE)
    local_x, local_z = x % CHUNK_SIZE, z % CHUNK_SIZE
    ground = surface_height(x, z)
    assert y == ground + 3.0, "find_spawn and surface_height disagree"

    top = max(y_ for y_ in range(CHUNK_HEIGHT)
              if blocks[local_x, y_, local_z] in GROUND)
    assert top == ground, f"predicted ground {ground}, chunk built {top}"
    return x, y, z


def report(chunks):
    # Sampled finely enough to see the rare ones: the mountain biomes are a few
    # tenths of a percent each, and at a coarser step they read as absent even
    # when they are there — which is how they stayed broken for a while.
    biomes = collections.Counter()
    for world_x in range(-9000, 9000, 113):
        for world_z in range(-9000, 9000, 113):
            biomes[BIOME_NAMES[column_biome(world_x, world_z)]] += 1
    total = sum(biomes.values())
    print(f"\n{len(biomes)} biomes over {total} columns:")
    line = []
    for name, count in biomes.most_common():
        line.append(f"{name} {count*100.0/total:.2f}%")
    print("  " + ", ".join(line))
    assert len(biomes) == len(BIOME_NAMES), \
        f"missing entirely: {sorted(set(BIOME_NAMES) - set(biomes))}"
    assert biomes.most_common(1)[0][1] / total < 0.35, "one biome swallowed the world"

    heights = np.array([surface_height(x, z)
                        for x in range(-9000, 9000, 113)
                        for z in range(-9000, 9000, 113)])
    print(f"height  min {heights.min()}  p50 {int(np.median(heights))}  "
          f"p95 {int(np.percentile(heights, 95))}  max {heights.max()}  "
          f"(sea {SEA_LEVEL}, {100*(heights < SEA_LEVEL).mean():.0f}% under water)")

    buffers = make_mesh_buffers()
    keys = sorted(chunks)
    inner = [k for k in keys if all((k[0] + dx, k[1] + dz) in chunks
                                    for dx, dz in ((-1, 0), (1, 0), (0, -1), (0, 1)))]

    def mesh():
        quads = 0
        for chunk_x, chunk_z in inner:
            neighbours = (chunks[(chunk_x - 1, chunk_z)], chunks[(chunk_x + 1, chunk_z)],
                          chunks[(chunk_x, chunk_z - 1)], chunks[(chunk_x, chunk_z + 1)])
            v, i, tv, ti = build_chunk_mesh_fast(chunks[(chunk_x, chunk_z)], chunk_x,
                                                 chunk_z, neighbours, *buffers,
                                                 FACE_LAYER, OPAQUE, 0)
            quads += (len(v) // 7 + len(tv) // 7) // 4
        return quads

    mesh()
    start = time.perf_counter()
    quads = mesh()
    mesh_ms = (time.perf_counter() - start) * 1000 / len(inner)

    start = time.perf_counter()
    for chunk_x, chunk_z in keys:
        gen(chunk_x, chunk_z)
    gen_ms = (time.perf_counter() - start) * 1000 / len(keys)

    tops = [max(column_top(b, x, z) for x in range(CHUNK_SIZE) for z in range(CHUNK_SIZE))
            for b in chunks.values()]
    print(f"terrain {gen_ms:.3f} ms/chunk   mesh {mesh_ms:.3f} ms/chunk   "
          f"{quads/len(inner):.0f} quads/chunk   highest block {int(np.mean(tops))}")


def check_trees():
    """Every shape fits inside PAD, and every crown is a crown.

    Two failures this catches, both of which have happened:

    * a shape that reaches further than PAD sideways. Trees are placed over a
      padded heightmap, and a canopy is only whole because both chunks either
      side of a seam derive it from the same hash — a shape that reaches PAD+1
      is simply not generated by the chunk it spills into, and the seam grows a
      bitten-off edge that nothing else in this file would notice.
    * crowns eaten away by `_leaves`' fray, or grown out of proportion. The
      fray thins a canopy from its *rim*, so it leaves no interior holes and no
      gap in any row — measured, neither a hole count nor a row-span fill can
      tell a full crown from one missing two fifths of its outline. What does is
      the plain leaf count, and one total over all fourteen shapes is enough:
      restoring the fray values this file was written against drops it from 816
      to 630, and doubling any crown's radius takes it well past the top of the
      band. Trees really are these sizes on purpose — the trunk heights and
      foliage radii are the reference's own `configured_feature` numbers — so a
      drift either way wants a look, not a silent retune of the bound.
    """
    out = []
    centre = CHUNK_SIZE // 2
    for shape in range(1, 15):
        blocks = np.zeros((CHUNK_SIZE, CHUNK_HEIGHT, CHUNK_SIZE), dtype=BLOCK_DTYPE)
        place_tree(blocks, centre, 40, centre, shape, 7, 6, 1234, 5678)
        leaf = np.argwhere(blocks == 6)
        wood = np.argwhere(blocks == 7)
        assert len(wood), f"shape {shape} grew no trunk"
        reach = int(np.abs(np.concatenate((leaf, wood))[:, [0, 2]] - centre).max())
        assert reach <= PAD, (f"shape {shape} reaches {reach} sideways, past "
                              f"PAD={PAD} — it will be clipped at chunk seams")
        out.append((shape, len(leaf), reach))
    total = sum(n for _s, n, _r in out)
    assert 700 <= total <= 1000, (
        f"the fourteen shapes carry {total} leaves between them, outside 700-1000 "
        f"— canopies have thinned out or ballooned: {out}")
    return out, total


if __name__ == '__main__':
    check_deterministic()
    print("same seed, same world")

    chunks = patch(30, -18, 5)
    check_bounds(chunks)
    check_water(chunks)
    check_caves(chunks)
    # The seam check needs trees to count, so it runs on a wooded patch rather
    # than on whatever the first one happened to be. Which patch is wooded moves
    # every time the terrain is retuned, so it is searched for, not written down.
    ratio = check_seams(wooded_patch(5))
    print(f"caves stay {SEAL_COVER}+ blocks under the surface, "
          f"canopies cross seams (chunk-edge leaf density {ratio:.0%} of mid-chunk)")

    shapes, leaves = check_trees()
    print(f"{len(shapes)} tree shapes, none reaching past PAD={PAD}, "
          f"{leaves} leaves between them "
          f"({min(n for _s, n, _r in shapes)}-{max(n for _s, n, _r in shapes)} each)")

    village_x, village_z, style, walls, kinds = check_village()
    print(f"village at ({village_x}, {village_z}), style {style}, {walls} wall "
          f"blocks, built from {', '.join(kinds)}")
    print("spawn at (%.1f, %.1f, %.1f)" % check_spawn())

    report(chunks)
    print("\nok")
